version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - vector-search

  frontend:
    build: ./frontend/rag-app
    container_name: rag_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  vector-search:
    image: facebook/faiss
    ports:
      - "8080:8080"
