
services:
  backend:
    image: ghcr.io/mollyiverson/acme10-he-ragapp-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: ghcr.io/mollyiverson/acme10-he-ragapp-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend