FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Download large files from Google Drive
RUN wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1yBHpx2klG9iRNOmwLcGQjhrwfvE5dNd4" -O /app/data_processing/embeddings_data/text_embeddings.npy && \
    wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1MP7DsnWATIWCR7xBNaVLzSuVnSEX6XFL" -O /app/data_processing/vector_search_data/index.faiss

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
