FROM python:3.9-slim

WORKDIR /app

LABEL org.opencontainers.image.source="https://github.com/mollyiverson/ACME10-HE-RAGApp"

# Needed to downloaded from Google Drive
RUN apt-get update && apt-get install -y wget

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Download large files from Google Drive. Comment out if you're building locally and have text_embeddings.npy and index.faiss
RUN wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1TyTSuojE9wMWSUXMrC31atVkX2wcm3s-" -O /app/data_processing/embeddings_data/text_embeddings.npy && \
    wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1aKMoiQpy9LoKpK0XdPptw_TUNm-I9U_0" -O /app/data_processing/vector_search_data/index.faiss

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
