FROM node:18-alpine AS builder

WORKDIR /app

LABEL org.opencontainers.image.source="https://github.com/mollyiverson/ACME10-HE-RAGApp"

COPY package.json package-lock.json ./
RUN npm install

COPY . ./

RUN npm run build

# Use a lightweight web server to serve the frontend
FROM nginx:alpine 

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
